version: '3'

services:
  mongo0:
    image: mongo
    restart: always
    volumes:
      - ./keyfile:/etc/keyfile
      - ./replication-mongo.sh:/start.sh
    command: bash start.sh
    ports:
      - 27017:27017
  mongo1:
    image: mongo
    restart: always
    volumes:
      - ./keyfile:/etc/keyfile
      - ./replication-mongo.sh:/start.sh
    command: bash start.sh
    ports:
      - 27018:27017
  mongo2:
    image: mongo
    restart: always
    volumes:
      - ./keyfile:/etc/keyfile
      - ./replication-mongo.sh:/start.sh
    command: bash start.sh
    ports:
      - 27019:27017
